// Generated by gencpp from file survey_and_rescue/SRBeaconStats.msg
// DO NOT EDIT!


#ifndef SURVEY_AND_RESCUE_MESSAGE_SRBEACONSTATS_H
#define SURVEY_AND_RESCUE_MESSAGE_SRBEACONSTATS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace survey_and_rescue
{
template <class ContainerAllocator>
struct SRBeaconStats_
{
  typedef SRBeaconStats_<ContainerAllocator> Type;

  SRBeaconStats_()
    : FOOD()
    , MEDICINE()
    , RESCUE()  {
    }
  SRBeaconStats_(const ContainerAllocator& _alloc)
    : FOOD(_alloc)
    , MEDICINE(_alloc)
    , RESCUE(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _FOOD_type;
  _FOOD_type FOOD;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _MEDICINE_type;
  _MEDICINE_type MEDICINE;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _RESCUE_type;
  _RESCUE_type RESCUE;





  typedef boost::shared_ptr< ::survey_and_rescue::SRBeaconStats_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::survey_and_rescue::SRBeaconStats_<ContainerAllocator> const> ConstPtr;

}; // struct SRBeaconStats_

typedef ::survey_and_rescue::SRBeaconStats_<std::allocator<void> > SRBeaconStats;

typedef boost::shared_ptr< ::survey_and_rescue::SRBeaconStats > SRBeaconStatsPtr;
typedef boost::shared_ptr< ::survey_and_rescue::SRBeaconStats const> SRBeaconStatsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::survey_and_rescue::SRBeaconStats_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::survey_and_rescue::SRBeaconStats_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace survey_and_rescue

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'survey_and_rescue': ['/home/itachi/catkin_ws/src/survey_and_rescue/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::survey_and_rescue::SRBeaconStats_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::survey_and_rescue::SRBeaconStats_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::survey_and_rescue::SRBeaconStats_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::survey_and_rescue::SRBeaconStats_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::survey_and_rescue::SRBeaconStats_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::survey_and_rescue::SRBeaconStats_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::survey_and_rescue::SRBeaconStats_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a79cd048d1c2632f303ccd4ac3fc8908";
  }

  static const char* value(const ::survey_and_rescue::SRBeaconStats_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa79cd048d1c2632fULL;
  static const uint64_t static_value2 = 0x303ccd4ac3fc8908ULL;
};

template<class ContainerAllocator>
struct DataType< ::survey_and_rescue::SRBeaconStats_<ContainerAllocator> >
{
  static const char* value()
  {
    return "survey_and_rescue/SRBeaconStats";
  }

  static const char* value(const ::survey_and_rescue::SRBeaconStats_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::survey_and_rescue::SRBeaconStats_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8[] FOOD\n\
uint8[] MEDICINE\n\
uint8[] RESCUE\n\
";
  }

  static const char* value(const ::survey_and_rescue::SRBeaconStats_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::survey_and_rescue::SRBeaconStats_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.FOOD);
      stream.next(m.MEDICINE);
      stream.next(m.RESCUE);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SRBeaconStats_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::survey_and_rescue::SRBeaconStats_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::survey_and_rescue::SRBeaconStats_<ContainerAllocator>& v)
  {
    s << indent << "FOOD[]" << std::endl;
    for (size_t i = 0; i < v.FOOD.size(); ++i)
    {
      s << indent << "  FOOD[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.FOOD[i]);
    }
    s << indent << "MEDICINE[]" << std::endl;
    for (size_t i = 0; i < v.MEDICINE.size(); ++i)
    {
      s << indent << "  MEDICINE[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.MEDICINE[i]);
    }
    s << indent << "RESCUE[]" << std::endl;
    for (size_t i = 0; i < v.RESCUE.size(); ++i)
    {
      s << indent << "  RESCUE[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.RESCUE[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SURVEY_AND_RESCUE_MESSAGE_SRBEACONSTATS_H
