// Generated by gencpp from file survey_and_rescue/yo.msg
// DO NOT EDIT!


#ifndef SURVEY_AND_RESCUE_MESSAGE_YO_H
#define SURVEY_AND_RESCUE_MESSAGE_YO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace survey_and_rescue
{
template <class ContainerAllocator>
struct yo_
{
  typedef yo_<ContainerAllocator> Type;

  yo_()
    : location()
    , info()  {
    }
  yo_(const ContainerAllocator& _alloc)
    : location(_alloc)
    , info(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _location_type;
  _location_type location;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _info_type;
  _info_type info;





  typedef boost::shared_ptr< ::survey_and_rescue::yo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::survey_and_rescue::yo_<ContainerAllocator> const> ConstPtr;

}; // struct yo_

typedef ::survey_and_rescue::yo_<std::allocator<void> > yo;

typedef boost::shared_ptr< ::survey_and_rescue::yo > yoPtr;
typedef boost::shared_ptr< ::survey_and_rescue::yo const> yoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::survey_and_rescue::yo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::survey_and_rescue::yo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace survey_and_rescue

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'survey_and_rescue': ['/home/itachi/catkin_ws/src/survey_and_rescue/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::survey_and_rescue::yo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::survey_and_rescue::yo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::survey_and_rescue::yo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::survey_and_rescue::yo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::survey_and_rescue::yo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::survey_and_rescue::yo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::survey_and_rescue::yo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "086e73c5fbed997f9c9e944f67f1b4d9";
  }

  static const char* value(const ::survey_and_rescue::yo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x086e73c5fbed997fULL;
  static const uint64_t static_value2 = 0x9c9e944f67f1b4d9ULL;
};

template<class ContainerAllocator>
struct DataType< ::survey_and_rescue::yo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "survey_and_rescue/yo";
  }

  static const char* value(const ::survey_and_rescue::yo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::survey_and_rescue::yo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string location\n\
string info\n\
";
  }

  static const char* value(const ::survey_and_rescue::yo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::survey_and_rescue::yo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.location);
      stream.next(m.info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct yo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::survey_and_rescue::yo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::survey_and_rescue::yo_<ContainerAllocator>& v)
  {
    s << indent << "location: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.location);
    s << indent << "info: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SURVEY_AND_RESCUE_MESSAGE_YO_H
